version: '3'
services:
  web:
    image: python:3.9
    ports:
      - 5000:5000
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "pip install --no-cache-dir -r requirements.txt && python app.py"
